spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: demo1
          uri: http://localhost:8081/demo1
          predicates:
            - Path=/demo1
        - id: demo2
          uri: http://localhost:8082/demo2
          predicates:
            - Path=/demo2